//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANPHUCVU1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANPHUCVU1()
        {
            this.CHITIETBANPHUCVUs = new HashSet<CHITIETBANPHUCVU1>();
            this.HOADONs = new HashSet<HOADON1>();
            this.BANANs = new HashSet<BANAN1>();
        }
    
        public string maPV { get; set; }
        public string maKH { get; set; }
        public string maTK { get; set; }
        public string soNguoi { get; set; }
        public System.DateTime thoiGianVao { get; set; }
        public bool coXoa { get; set; }
    
        public virtual KHACHHANG1 KHACHHANG { get; set; }
        public virtual TAIKHOAN1 TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBANPHUCVU1> CHITIETBANPHUCVUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON1> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANAN1> BANANs { get; set; }
    }
}
