//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETCALAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIETCALAM()
        {
            this.PHANCONGCALAMs = new HashSet<PHANCONGCALAM>();
        }
    
        public string maCT { get; set; }
        public System.DateTime ngayLam { get; set; }
        public System.TimeSpan gioBatDau { get; set; }
        public System.TimeSpan gioKetThuc { get; set; }
        public bool trangThai { get; set; }
        public int soLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONGCALAM> PHANCONGCALAMs { get; set; }
    }
}
