//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATBAN
    {
        public int iD { get; set; }
        public string maBan { get; set; }
        public string maPV { get; set; }
    
        public virtual BANAN BANAN { get; set; }
        public virtual BANPHUCVU BANPHUCVU { get; set; }
    }
}
