//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON1
    {
        public string maHD { get; set; }
        public string maTK { get; set; }
        public string maPV { get; set; }
        public System.DateTime ngayThanhToan { get; set; }
        public decimal tongTien { get; set; }
    
        public virtual BANPHUCVU1 BANPHUCVU { get; set; }
        public virtual TAIKHOAN1 TAIKHOAN { get; set; }
    }
}
