//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG1()
        {
            this.BANPHUCVUs = new HashSet<BANPHUCVU1>();
        }
    
        public string maKH { get; set; }
        public string tenKH { get; set; }
        public string SDT { get; set; }
        public bool gioiTinh { get; set; }
        public string diaChi { get; set; }
        public int diemTichLuy { get; set; }
        public Nullable<bool> coXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANPHUCVU1> BANPHUCVUs { get; set; }
    }
}
