//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONGNHANVIEN
    {
        public int iD { get; set; }
        public string maTK { get; set; }
        public string tenNV { get; set; }
        public string thangLam { get; set; }
        public double soGioLam { get; set; }
        public double luongTheoGio { get; set; }
        public double tongLuong { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
