//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONAN()
        {
            this.CHITIETBANPHUCVUs = new HashSet<CHITIETBANPHUCVU>();
        }
    
        public string maMA { get; set; }
        public string tenMA { get; set; }
        public string maLM { get; set; }
        public double giaMA { get; set; }
        public string donViTinh { get; set; }
        public byte[] anhMA { get; set; }
        public bool coXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBANPHUCVU> CHITIETBANPHUCVUs { get; set; }
        public virtual LOAIMON LOAIMON { get; set; }
    }
}
