//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnPBL3.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNH_DB : DbContext
    {
        public QLNH_DB()
            : base("name=QLNH_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANAN> BANANs { get; set; }
        public virtual DbSet<BANPHUCVU> BANPHUCVUs { get; set; }
        public virtual DbSet<CHITIETBANPHUCVU> CHITIETBANPHUCVUs { get; set; }
        public virtual DbSet<CHITIETCALAM> CHITIETCALAMs { get; set; }
        public virtual DbSet<CHITIETDATBAN> CHITIETDATBANs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIMON> LOAIMONs { get; set; }
        public virtual DbSet<LUONGNHANVIEN> LUONGNHANVIENs { get; set; }
        public virtual DbSet<MONAN> MONANs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHANCONGCALAM> PHANCONGCALAMs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
